package com.trilhadev.app;

/**
 * Lista fixa de termos de desenvolvimento + significado (pt-BR), usada pelo
 * widget "Termo do dia". Sem dependência de rede — embutida no APK.
 */
final class DevTerms {

    static final String[][] LIST = {
        {"API", "Interface que permite dois sistemas conversarem entre si."},
        {"Framework", "Estrutura pronta que organiza como você escreve seu código."},
        {"Biblioteca", "Conjunto de funções prontas que você importa e usa no projeto."},
        {"Closure", "Função que \"lembra\" das variáveis do escopo onde foi criada."},
        {"Callback", "Função passada como argumento pra ser chamada depois, quando algo termina."},
        {"Promise", "Objeto que representa um valor que ainda vai existir (sucesso ou erro)."},
        {"Async/Await", "Jeito de escrever código assíncrono como se fosse síncrono."},
        {"Middleware", "Código que roda entre a requisição chegar e a resposta ser enviada."},
        {"Endpoint", "Endereço específico de uma API onde uma ação pode ser feita."},
        {"REST", "Estilo de arquitetura de API baseado em recursos e verbos HTTP."},
        {"CRUD", "Create, Read, Update, Delete — as 4 operações básicas sobre dados."},
        {"ORM", "Camada que traduz objetos do código em linhas de banco de dados."},
        {"Migration", "Script versionado que altera a estrutura do banco de dados."},
        {"Cache", "Guardar um resultado pra não recalcular ou rebuscar de novo."},
        {"CDN", "Rede de servidores espalhados que entrega arquivos mais perto do usuário."},
        {"DNS", "Sistema que traduz nomes de domínio em endereços IP."},
        {"CI/CD", "Automação que testa e publica o código a cada mudança."},
        {"Deploy", "Colocar uma nova versão do sistema no ar."},
        {"Rollback", "Voltar pra versão anterior depois de um problema em produção."},
        {"Build", "Processo que transforma código-fonte em algo executável/publicável."},
        {"Repositório", "Onde o histórico e os arquivos de um projeto ficam versionados."},
        {"Commit", "Um \"salvamento\" de mudanças no histórico do Git, com mensagem."},
        {"Branch", "Linha paralela de desenvolvimento que não afeta a principal."},
        {"Merge", "Juntar as mudanças de uma branch em outra."},
        {"Pull Request", "Pedido pra revisar e juntar código de uma branch em outra."},
        {"Merge Conflict", "Quando duas mudanças mexem na mesma linha e o Git não sabe escolher."},
        {"Refactor", "Reorganizar código sem mudar o que ele faz."},
        {"Debug", "Processo de encontrar e corrigir um erro no código."},
        {"Stack Trace", "Lista de chamadas de função que levaram até um erro."},
        {"Exception", "Erro que interrompe o fluxo normal do programa em tempo de execução."},
        {"Null/Undefined", "Ausência de valor — causa comum de erro quando não tratado."},
        {"Variável", "Espaço nomeado na memória que guarda um valor."},
        {"Função Pura", "Função que sempre retorna o mesmo resultado pro mesmo input, sem efeito colateral."},
        {"Efeito Colateral", "Quando uma função altera algo fora dela (estado global, arquivo, tela)."},
        {"Recursão", "Função que chama a si mesma pra resolver um problema menor."},
        {"Loop", "Estrutura que repete um bloco de código várias vezes."},
        {"Array", "Lista ordenada de valores acessados por índice."},
        {"Objeto", "Estrutura de dados com pares de chave e valor."},
        {"JSON", "Formato de texto pra representar dados estruturados, usado em APIs."},
        {"Serialização", "Transformar um dado em memória em um formato que pode ser salvo/enviado."},
        {"Tipagem Estática", "Quando o tipo de cada variável é checado antes de rodar (ex: TypeScript)."},
        {"Tipagem Dinâmica", "Quando o tipo de uma variável só é checado enquanto o programa roda."},
        {"Compilador", "Programa que traduz código-fonte pra outra linguagem antes de rodar."},
        {"Interpretador", "Programa que executa o código linha a linha, sem compilar antes."},
        {"Runtime", "Ambiente onde o código realmente executa (ex: Node.js, JVM)."},
        {"Garbage Collector", "Parte da linguagem que libera memória não usada automaticamente."},
        {"Thread", "Linha de execução independente dentro de um programa."},
        {"Concorrência", "Várias tarefas avançando ao mesmo tempo (não necessariamente juntas)."},
        {"Paralelismo", "Várias tarefas rodando de verdade ao mesmo tempo, em núcleos diferentes."},
        {"Race Condition", "Bug que só acontece dependendo da ordem em que coisas paralelas terminam."},
        {"Deadlock", "Quando duas partes do sistema ficam esperando uma pela outra pra sempre."},
        {"Singleton", "Padrão que garante que só existe uma instância de algo no sistema."},
        {"Factory", "Padrão onde uma função/classe cria objetos em vez de usar \"new\" direto."},
        {"Injeção de Dependência", "Passar as dependências de um componente por fora, em vez de criar dentro dele."},
        {"Componente", "Pedaço reutilizável de interface, com sua própria lógica e visual."},
        {"Estado (State)", "Dado que muda ao longo do tempo e afeta o que é mostrado na tela."},
        {"Props", "Dados passados de um componente pai pra um componente filho."},
        {"Hook", "Função especial (React) que dá acesso a estado/efeitos dentro de um componente."},
        {"Virtual DOM", "Representação em memória da tela, usada pra atualizar só o que mudou."},
        {"Renderização", "Processo de transformar dados/estado em algo visível na tela."},
        {"Responsivo", "Layout que se adapta a diferentes tamanhos de tela."},
        {"Acessibilidade (a11y)", "Tornar um app usável por pessoas com deficiência."},
        {"Latência", "Tempo entre pedir algo e começar a receber a resposta."},
        {"Throughput", "Quantidade de trabalho que um sistema consegue processar por tempo."},
        {"Escalabilidade", "Capacidade de um sistema aguentar mais carga sem quebrar."},
        {"Load Balancer", "Distribui as requisições entre vários servidores."},
        {"Microsserviço", "Sistema dividido em serviços pequenos e independentes."},
        {"Monólito", "Sistema inteiro rodando como uma única aplicação."},
        {"Container", "Empacota o app com tudo que ele precisa pra rodar igual em qualquer lugar."},
        {"Variável de Ambiente", "Configuração externa ao código (ex: senha de banco), não fica no fonte."},
        {"Autenticação", "Confirmar quem é o usuário (ex: login)."},
        {"Autorização", "Definir o que um usuário autenticado tem permissão de fazer."},
        {"Token", "Código que representa uma sessão/permissão autenticada, sem precisar reenviar senha."},
        {"Hash", "Transformação de um dado em um valor de tamanho fixo, difícil de reverter."},
        {"Criptografia", "Técnica pra proteger dados de forma que só quem tem a chave lê."},
        {"SQL Injection", "Ataque que insere comandos SQL maliciosos por um campo de entrada."},
        {"XSS", "Ataque que injeta script malicioso numa página vista por outros usuários."},
        {"CORS", "Regra do navegador que controla quais sites podem chamar sua API."},
        {"Webhook", "Um sistema avisa o outro automaticamente quando algo acontece, via HTTP."},
        {"WebSocket", "Conexão que fica aberta pra troca de dados em tempo real."},
        {"Idempotência", "Fazer a mesma operação várias vezes tem o mesmo efeito que fazer uma vez."},
        {"Lint", "Ferramenta que aponta erros e problemas de estilo no código antes de rodar."},
        {"Teste Unitário", "Teste que verifica uma única peça pequena do código isoladamente."},
        {"Teste de Integração", "Teste que verifica se várias partes do sistema funcionam juntas."},
        {"Mock", "Versão falsa de algo (API, banco) usada só pra testar sem depender do real."},
        {"Legacy", "Código antigo, geralmente sem testes/documentação, difícil de mexer."},
        {"Débito Técnico", "Atalho tomado agora que vai custar trabalho extra pra corrigir depois."},
    };

    private DevTerms() {}
}
